### ISSUE TITLE
E16: Celestinine Mountain 2F -> B2F

### ISSUE THREAD

**Issue by DimlyMoonbeam** [BIGJRA/BIGJRA.github.io#4]
Looks like this should be B2F.

https://bigjra.github.io/reborn.html#iolia-valley--aventurine-woods-water-exploration
> Make your way all the way to the left to the entrance of North Aventurine Woods that leads to Celestinine Mountain 2F.

Screen transition:
https://user-images.githubusercontent.com/6762962/210035614-5f48a7ba-6ca5-487d-8452-c7246c8364e7.mp4

**Comment by BIGJRA** [comment]
Thanks for the report!
